# KAYNAK domainin server bloğu. Tüm istekleri .com'a 301.
server {
    listen 80;
    listen 443 ssl;
    server_name kozbeylikonagi.com.tr www.kozbeylikonagi.com.tr
                kozbeylikonagiotel.com www.kozbeylikonagiotel.com;
    return 301 https://www.kozbeylikonagi.com$request_uri;
}
